---
- name: Update System
  apt:
    update_cache: yes

- name: Enabling GPU Support
  command: kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.7.2/nvidia-device-plugin.yml
  become_user: ubiq

- name: Remove taint
  command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
  become_user: ubiq

- name: Run Helm Installation
  include_tasks: install_helm.yaml

- name: Run Dashboard Installation on K8s
  include_tasks: install_dashboard.yaml

- name: Run MinIO Installation on K8s
  include_tasks: install_minio.yaml

- name: Run KubVirt Installation on K8s
  include_tasks: install_kubevirt.yaml
