- name: Windows-Teste
  hosts: all
  tasks:
    - name: Run stop service under PowerShell
      win_shell: Get-Service -name wuauserv | stop-service
    - name: Run start PowerShell
      win_shell: Get-Service -name wuauserv | start-service
